from typing import Literal, Optional, Any, TypedDict

from pydantic import BaseModel, ConfigDict, Field

# ----------------------------------------
#       CONVERSATION AGENT OUTPUT
# ----------------------------------------

class ConversationAgentOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    response: str = Field(
        default="",
        description="The final user-facing response generated by the conversation agent."
    )

    response_type: Literal[
        "answer",
        "clarification",
        "acknowledgement",
        "confirmation",
        "status",
        "error",
    ] = Field(
        default="error",
        description="The semantic type of the generated response."
    )

    error: Optional[str] = Field(
        default=None,
        description="Error information populated by the conversation agent wrapper when execution fails."
    )

# ----------------------------------------
#       CONVERSATION AGENT INPUT
# ----------------------------------------


class ConversationMessage(TypedDict):
    role: str
    content: str


class RuntimeState(TypedDict):
    task: str
    input: Any
    steps: list[dict[str, Any]]
    recent_conversations: list[ConversationMessage]


class RelevantContext(TypedDict):
    episodic_memory: list[dict[str, Any]]
    chat_archives: list[dict[str, Any]]
    learned_knowledge: list[dict[str, Any]]


class ExecutionContext(TypedDict):
    actions: list[dict[str, Any]]
    results: list[dict[str, Any]]
    failures: list[dict[str, Any]]


class ConversationAgentState(TypedDict):
    user_request: str
    objective: str
    recent_conversations: list[ConversationMessage]
    relevant_context: RelevantContext
    runtime_state: RuntimeState
    execution_context: ExecutionContext